version: '{build}'
image: Visual Studio 2017

init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true") {
      $env:PackageVersionBase = ${env:APPVEYOR_REPO_TAG_NAME}.Substring(1)
      $env:PackageVersionSuffix = ""
    }

    else {
      $env:PackageVersionBase = "0.0.0"
      $env:PackageVersionSuffix = "-b${env:APPVEYOR_BUILD_NUMBER}"
    }

    "PackageVersionBase: ${env:PackageVersionBase}"

    "PackageVersionSuffix: ${env:PackageVersionSuffix}"

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(PackageVersionBase)$(PackageVersionSuffix)
  file_version: $(PackageVersionBase).{build}

build_script:
- cmd: >-
    cd src

    dotnet build -c Release

    dotnet pack Manisero.Navvy -c Release --include-symbols --no-build

    dotnet pack Manisero.Navvy.Dataflow -c Release --include-symbols --no-build

    dotnet pack Manisero.Navvy.Reporting -c Release --include-symbols --no-build

test_script:
- cmd: >-
    dotnet test Manisero.Navvy.Tests -c Release --no-build

artifacts:
- path: '**\bin\Release\*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: PJDYQXbeNuvR8SBLTJFkG+pCdEnTwjsT4M7ULv2wFQTUJUen5afHeigdYJCfqbiq
  on:
    appveyor_repo_tag: true
