version: '{build}'
image: Visual Studio 2017

build_script:
- cmd: >-
    cd src

    dotnet build -c Release

    dotnet test Manisero.Navvy.Tests -c Release --no-build

    dotnet pack Manisero.Navvy -c Release --include-symbols --no-build

    dotnet pack Manisero.Navvy.Dataflow -c Release --include-symbols --no-build

deploy:
- provider: NuGet
  api_key:
    secure: SJhz4UnOzI1RS5gzQoav6HbCDis5x7d8QzICFmtX9TuHIOGKXpUtEwwELptoqiZj
  on:
    appveyor_repo_tag: true
